config/routes.rb
Rails.application.routes.draw do
 
  root('guests#index')
  get('/about', to: 'guests#about')

  resources(:users, only: %i[index new show edit create update])
  resources(:accounting_object, except: %i[create])
  resources(:categories, except: %i[new show])
  resources(:operations, except: %i[show])

  resource(:session, only: %i[new create destroy])
  #resource(:password_reset, only: %i[new create edit update])

  post('accounting_object_psot', to: 'accounting_object#create', as: 'accounting_object_post')

end

app/models/accounting_object.rb
class AccountingObject < ApplicationRecord
  belongs_to :user
  belongs_to :type_object
  belongs_to :kind_of_object
  
  has_many :category, dependent: :destroy

  validates(:user, presence: true)
  validates(:type_object, presence: true)
  validates(:kind_of_object, presence: true)
  validates(:name_object, { presence: true, length: {minimum: 1, maximum: 64 }, uniqueness: { scope: :user_id }})
  validates(:type_object_id, inclusion: { in: [1, 2] })

end

app/controllers/accounting_object_controller.rb
class AccountingObjectController < ApplicationController

  before_action(:require_authentication)

  def index
    user = User.find_by(remember_token_digest: session[:user_id])
    @accounting_objects = user.accounting_object.order(id: :desc)
  
    @accounting_object_new = AccountingObject.new
    @select_kind_of_object = KindOfObject.all
  end

  def new
    @accounting_object_new = AccountingObject.new
    @select_kind_of_object = KindOfObject.all
  end

  def show
   
    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object_decript = Base64.decode64(params[:id])
      @date_end = Time.now
      @date_start = @date_end.minus_with_duration(30.days)

    if params['[date_field_operations]'].present? then
      begin
        @date_start = Time.parse(params['[date_field_operations]'][:date_start]).beginning_of_day 
        @date_end = Time.parse(params['[date_field_operations]'][:date_end]).end_of_day #|| Time.now
      rescue ArgumentError => e
        @date_end = Time.now
        @date_start = @date_end.minus_with_duration(30.days)
      end
    end

    if user.accounting_object_ids.include?(acc_object_decript.to_i) then
      @acc_object = AccountingObject.find(acc_object_decript)
      @acc_object_encript =  Base64.encode64(@acc_object.id.to_s)

      @pagy, @all_operation_for_acc_object = pagy Operation
      .where(accounting_object_id: @acc_object.id)
      .where(created_at: @date_start..@date_end)
      .order(created_at: :desc)

      #@all_sum = @all_operation_for_acc_object.sum(:amount_of_money)

      money_category = {}
      temp_arr = []
      category_colors = {}

      @all_operation_for_acc_object.each do |op|
        money_category[op.category.name_category] = 0
      end

      @all_operation_for_acc_object.each do |op|
        temp_arr.push([op.category.name_category, op.amount_of_money.to_i])
        category_colors[op.category.name_category] = op.category.color_category.delete(';')
      end

      temp_arr.each do |arr|
        money_category[arr[0]] += arr[1]
      end

      @data_category_chart = {data_name_and_money: money_category, data_colors: category_colors}

      
=begin
      @all_operation_group_by_category_id = Operation
      .where(accounting_object_id: @acc_object.id)
      .where(created_at: @date_start..@date_end)
      .group(:category_id).count

      @all_operation_to_chart = @all_operation_group_by_category_id.inject({}) do |result, (k, v)| 
        result[Category.find(k).name_category]=v 
        result
      end
=end

      render(:show)
    else
      flash.now[:message] = '1 error from accounting_object#show'
      redirect_to(root_path)
    end

  end

  def create

    user = User.find_by(remember_token_digest: session[:user_id])
    params_create = accounting_object_params.merge!(user_id: user.id)
    acc_object = AccountingObject.new(params_create)

    if acc_object.save then
      flash.now[:message] = 'acc_object created'
      redirect_to(accounting_object_index_path)
    else
      @accounting_object_new = acc_object
      @select_kind_of_object = KindOfObject.all

      #flash[:message] = acc_object.errors.full_messages
      render(:new)
    end
  
  end

  def edit

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object_decript = Base64.decode64(params[:id])
    acc_object = AccountingObject.find(acc_object_decript)


    if user.id == acc_object.user_id then
      @select_kind_of_object = KindOfObject.all
      @acc_object_user = acc_object
    else
      redirect_to(root_path)
    end
  end

  def update

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object = AccountingObject.find(params[:id])

    if user.id == acc_object.user_id then

      if acc_object.update(accounting_object_params) then        
        redirect_to(accounting_object_index_path)
      else
        @accounting_object_new = AccountingObject.new
        @select_kind_of_object = KindOfObject.all
        @acc_object_user = acc_object

        render(:edit)
      end

    else
      flash[:message] = '1 error from accounting_object#update'
      redirect_to(root_path)
    end
  end

  def destroy

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object = AccountingObject.find(params[:id])

    if user.id == acc_object.user_id then

      if acc_object.destroy then
        flash[:message] = 'acc_object delete'
        redirect_to(root_path)
      else
        flash[:message] = '2 error from accounting_object#delete'
        render(:new)
      end
      
    else
      flash[:message] = '1 error from accounting_object#delete'
      redirect_to(root_path)
    end
  
  end

  private

  def accounting_object_params
    cleared_params = {}

    cleared_params.merge!(params.require(:accounting_object).permit(:name_object, :type_object_id))
    cleared_params.merge!(params.require(:select_kind).permit(:kind_of_object_id))
  end

end

app/views/accounting_object/_form.html.erb
<div class="content-section-create-object">
	<div class="content-new-form-container-create-object">
		<div class="content-form-create-object">
					
		<%= form_with(model: accounting_object,						
						url: url,
						method: method_action,
						data: {turbo: false}
						) do |f|  %>	

			<div class="user-setting-header-bottom size-xl">
		    	<h2><%= accounting_object.persisted? ? t('form.acc_boject.update_object') : t('form.acc_boject.create_object')  %></h2>
		    </div>								

		    <div class="form-container-field-object">
		    	<%= f.label(:name_object, 'Название объекта:', class: 'm-top-m size-xl') %>
		    	<%= f.text_field(:name_object, class: 'form-input-create-object size-xl m-top-s', required: true) %>

			    <div class="text-bottom-create-object size-l">
					Придумайте название для вашего объекта 
					по которому вы планируете всести учет. 
					Наприме: дом, автомобиль, хобби.					
				</div>
		    </div>

		    <div>
		    	<hr class="drop-line-form">
		    </div>

		    <div class="user-setting-header-bottom size-xl">
		    	<span>Выберите тип</span>
		    </div>
		    
		    <div class="form-radio-btn-container">
		    	<input id="radio-test-object" type="radio" name="accounting_object[type_object_id]" value="3" hidden checked>

					<div class="form-radio-btn size-xl">
						<input id="radio-income-object" type="radio" name="accounting_object[type_object_id]" value="2">
						<label for="radio-income-object" id="radio-income-object-label" ><%= t('acc_boject.income') %></label>
					</div>

					<div class="form-radio-btn size-xl">
						<input id="radio-expense-object" type="radio" name="accounting_object[type_object_id]" value="1">
						<label for="radio-expense-object" id="radio-expense-object-label"><%= t('acc_boject.expense') %></label>
					</div>
				 
		    </div>

		    <div>
		    	<hr class="drop-line-form">
		    </div>


		    <div class="user-setting-header-bottom size-xl">
		    	<span>Вид вашего объекта</span>
		    </div>

		    <div class="form-select-container-object">
		    	<div style="display: grid; place-items: center;">
		    		<span class="size-xl">Вид объекта:</span>
		    	</div>

		    	<div>
		    		<%# select('select_kind', :kind_of_object_id, 
		    		select_kind_of_object.collect { |p| [t("form.select_kind#{p.name_kind}"), p.id] }
		    		)  %>
		    	</div>
		    	<div>
		    		<%= select('select_kind', :kind_of_object_id, 
		    		select_kind_of_object.collect { |p| [t("form.select_kind.#{p.name_kind}"), p.id] }
		    		)  %>
		    	</div>
		    </div>

		    <div>
		    	<hr class="drop-line-form">
		    </div>

		    <div class="form-container-field-object m-top-xl m-bot-m">
		    	<%= f.submit(create_or_update(accounting_object), class: 'btn-create-object') %>
		    </div>
		  
		<% end %>

	    <% if accounting_object.persisted? then  %>
				<div>
				    <hr class="drop-line-form">
				</div>

	    	<div class="form-container-field-object m-bot-xl m-top-m">
				<%= button_to(t('btn.delete'), 
				"/accounting_object/#{accounting_object.id}", 
				method: :delete, 
				class: 'btn-delete-object', 
				id: 'delete-button'
				)  %>
	    	</div>
	    <% end %>

	    </div>
	</div>		
</div>		


<script>
    document.getElementById("delete-button").addEventListener("click", function(event){
      event.preventDefault(); // Предотвращаем стандартное поведение отправки формы
      
      if(confirm("Вы действительно хотите удалить этот объект?")) {
        this.form.submit(); // Отправляем форму, если пользователь подтвердил удаление
      }
    });
</script>

app/views/accounting_object/_show_chart.html.erb
<div class="chart-container">
	<%= pie_chart(@data_category_chart[:data_name_and_money],
		id: 'pie-chart', width: "100%", height: "40em",
		colors: @data_category_chart[:data_colors].values,		
	    legend: 'right',
	    responsive: true
	) %>
</div>

app/views/accounting_object/_show_objects.html.erb
<article class="content-container-main-center">
	<section class="content-section-table">

		<div class="user-setting-header size-xxl">
			<span>Список ваших объектов</span>
		</div>
		
		<table class="accounting-objects-table">
			<thead>
				<tr>
					<th><%= t('table.name_object')  %></th>
					<th><%= t('table.type_object_id')  %></th>
					<th style="text-align: center;"><%= t('table.kind_of_object_id')  %></th>
					<th><%# t('table.edit')  %></th>
					<th><%# t('table.show')  %></th>
					<th><%# t('table.add_record')  %></th>
				</tr>
			</thead>
			<tbody>
				<% accounting_objects.each do |acc_obj|  %>
				<tr>
					<td><%= acc_obj.name_object  %></td>
					<td class="type-object-id-<%= acc_obj.type_object_id%>">
						<%= t("acc_boject.#{acc_obj.type_object.name_type}")  %>
					</td>
					<td style="text-align: center;"><%= t("acc_boject.#{acc_obj.kind_of_object.name_kind}")  %></td>
					<td><%# link_to(t('btn.edit'), edit_accounting_object_path(Base64.encode64(acc_obj.id.to_s)))  %></td>
					<td><%= link_to(t('btn.show'), accounting_object_path(Base64.encode64(acc_obj.id.to_s)))  %></td>
					<td style="text-align: center;"><%= link_to(t('btn.add_record'), 
					new_operation_path(accounting_object_id: Base64.encode64(acc_obj.id.to_s))  
					)%></td>
				</tr>	
				<% end %>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="6"></td>
				</tr>
			</tfoot>			
		</table>

	</section>
</article>

app/views/accounting_object/_show_table.html.erb
<div class="zise-s">
	<table class="accounting-category-table">
		<thead>
			<tr>
				<th><%= t('table.number')  %></th>
				<th><%= t('table.category')  %></th>
				<th><%= t('table.data_stamp')  %></th>
				<th><%= t('table.amount_of_money')  %></th>
				<th><%= t('table.description')  %></th>
				<th><%= t('table.edit')  %></th>			
			</tr>
		</thead>
		<tbody>
			<% @all_operation_for_acc_object.each_with_index do |operation, i|  %>
			<tr>
				<td><%= i + 1 %></td>
				<td><%= operation.category.name_category %></td>
				<td><%= operation.data_stamp.to_date %></div></td>
				<td><%= operation.amount_of_money %></td>
				<td><%= operation.description %></td>
				<td><%= link_to(t('btn.edit'), 
					edit_operation_path(
					{id: Base64.encode64(operation.id.to_s), accounting_object_id: @acc_object_encript}
					))%></td>
			</tr>	
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="6"><%== pagy_nav(@pagy) %></td>
			</tr>
		</tfoot>			
	</table>
</div>

app/views/accounting_object/edit.html.erb
<article class="content-container-main-center">
	<section class="content-section">
		
		<% render('shared/errors', object_error: @acc_object_user ) %>

		<%= render(partial: 'form', locals: {
			accounting_object: @acc_object_user, 
			select_kind_of_object: @select_kind_of_object, 
			url: accounting_object_path(@acc_object_user.id),
			method_action: :patch}) %>
	</section>			
</article>

app/views/accounting_object/index.html.erb
<article class="content-container-main-center">
	<section class="content-section">
		<% if @accounting_objects.present? %>
			
			<%= render(partial: 'show_objects', locals: {accounting_objects: @accounting_objects})  %>
			
		<% else %>

			<%= render(partial: 'form', locals: {
				accounting_object: @accounting_object_new, 
				select_kind_of_object: @select_kind_of_object,
				url: accounting_object_post_path,
				method_action: :post}) %>

		<% end %>
	</section>
</article>

app/views/accounting_object/new.html.erb
<article class="content-container-main-center">
	<section class="content-section">

		<% render('shared/errors', object_error: @accounting_object_new ) %>

		<%= render(partial: 'form', locals: {
			accounting_object: @accounting_object_new, 
			select_kind_of_object: @select_kind_of_object,
			url: accounting_object_post_path,
			method_action: :post}) %>
	</section>
</article>	

app/views/accounting_object/show.html.erb
<article class="content-container-main-center">
	<section class="content-section">
		<div class="show-main-container-accounting">
			<div class="user-setting-header size-xxl">
				<span class="size-xxl"><%= @acc_object.name_object %></span>
			</div>

			<div class="show-container-accounting">					
				<div class="show-container-accounting-section-left">

					<div class="show-accounting-info-fields">
						<div>
							<span>Тип объекта:</span>
						</div>
						<div>
							<span class="show-accoutnting-type-object-<%= @acc_object.type_object_id%>">
								<%= t("acc_boject.#{@acc_object.type_object.name_type}") %>									
							</span>
						</div>
					</div>

					<div class="show-accounting-info-fields">
						<div>
							<span>Дата создания:</span>
						</div>
						<div>
							<span class="show-accoutnting-type-object-date">
								<%= @acc_object.created_at.to_date %>									
							</span>
						</div>
					</div>
					
					<%= form_with(url: accounting_object_path(Base64.encode64(@acc_object.id.to_s)),
						method: 'GET', 
						data: { turbo: false }) do |f| 
					%>

						<%= f.fields_for :date_field_operations do |ff| %>

							<div class="show-accounting-date-fields">								
								<%= ff.label(:date_start, 'Дата начало')  %>
								<%= ff.date_field(:date_start, value: @date_start, max: Time.now.to_date) %>
							</div>

							<div class="show-accounting-date-fields">
								<%= ff.label(:date_end, 'Дата конец')  %>
								<%= ff.date_field(:date_end, value: @date_end, max: Time.now.to_date) %>
							</div>

						<% end %>
						<div class="show-accounting-date-fields">							

							<div style="text-align: center;">							
								<button type="button" onclick="resetDates()" class="btn-date-reset size-l m-top-s">Отчистить </button>
							</div>	

							<div style="text-align: center;">
								<%= f.submit('Посмотреть', class: 'btn-date-show size-l m-top-s')  %>
							</div>

						</div>
					<% end %>

					
					<div>
    				<hr class="drop-line-form">
    			</div>

					<div class="select-data-view-container">
						<div>
							<span class="select-data-view-btn size-xl active-button" id="btn-to-table">Таблица</span>
						</div>

						<div>
							<span class="select-data-view-btn size-xl" id="btn-to-chart">График</span>
						</div>
					</div>

					<div class="select-data-view-container user-actions-container" >
						<div>
							<%= link_to(t('btn.add_record'), 
							new_operation_path(accounting_object_id: @acc_object_encript), 
							class: 'btn-user-action')  %>
						</div>

						<div>
							<%= link_to(t('btn.all_category'), 
							categories_path(accounting_object_id: @acc_object_encript), 
							class: 'btn-user-action')  %>
						</div>

						<div>
							<%= link_to(t('btn.edit_object'), 
							edit_accounting_object_path(Base64.encode64(@acc_object.id.to_s)), 
							class: 'btn-user-action')  %>
						</div>

						<div>
							<%= link_to(t('btn.report'), '#', class: 'btn-user-action')  %>
						</div>
					</div>
				</div>

				<div class="show-container-accounting-section-reight">
					<div id="table-content" class="active-content">						
						<%= render(partial: 'show_table')  %>
					</div>

					<div id="chart-content">
						<%= render(partial: 'show_chart')  %>
					</div>
				</div>
			</div>
		</div>
	</section>
</article>


<script>
  // Получаем существующие кнопки
  const btnToTable = document.getElementById('btn-to-table');
  const btnToChart = document.getElementById('btn-to-chart');

  // Получаем существующие контентные блоки
  const tableContent = document.getElementById('table-content');
  const chartContent = document.getElementById('chart-content');

  // Обработчик кликов по кнопкам
  function handleButtonClick(event) {
    const clickedBtn = event.target;


    // Удаляем активный класс у обеих кнопок
    [btnToTable, btnToChart].forEach(btn => btn.classList.remove('active-button'));

    // Устанавливаем активный класс на выбранную кнопку
    clickedBtn.classList.add('active-button');

    // Переключаем видимость контента
    if (clickedBtn === btnToTable) {
      chartContent.classList.remove('active-content');
      tableContent.classList.add('active-content');
    } else if (clickedBtn === btnToChart) {
      tableContent.classList.remove('active-content');
      chartContent.classList.add('active-content');
    }
  }

  // Назначаем обработчики событий на обе кнопки
  btnToTable.addEventListener('click', handleButtonClick);
  btnToChart.addEventListener('click', handleButtonClick);



    function resetDates() {
        document.getElementById('_date_field_operations_date_start').value = '';
        document.getElementById('_date_field_operations_date_end').value = '';
    }

</script>