config/routes.rb
Rails.application.routes.draw do
 
  root('guests#index')
  get('/about', to: 'guests#about')

  resources(:users, only: %i[index new show edit create update])
  resources(:accounting_object, except: %i[create])
  resources(:categories, except: %i[new show])
  resources(:operations, except: %i[show])

  resource(:session, only: %i[new create destroy])
  #resource(:password_reset, only: %i[new create edit update])

  post('accounting_object_psot', to: 'accounting_object#create', as: 'accounting_object_post')

end

app/views/shared/_dropdown_menu.html.erb
<div class="nav-bar-menu-sign">
	<% if user_signed_in? %>
		
		<div class="nav-bar-image-ball">
			<%= image_tag('bell-solid', class: 'nav-bar-img-user')  %>
		</div>

		<details class="nav-bar-dropdown-user">
		    <summary role="button">
		      <%= image_tag('user-solid', class: 'nav-bar-img-user') %>
		    </summary>
		    <ul>
			    <li><%= link_to(current_user.user_name, '#', class: 'drop-down-user-name size-xl')  %></li>
			    <li><%= link_to('Информация', user_path('user')) %></li>
			    <li><%= button_to('Выйти', session_path, method: :delete, data: {turbo: false})  %></li>			    			    
		  </ul>
		</details>

	<% else %>

		<div class="nav-bar-menu-sign">
			<%= link_to('Вход', new_session_path, class: 'sign-in') %>
			<%= link_to('Регистрация', new_user_path, class: 'sign-up') %>			
		</div>
	
	<% end %>
</div>

app/views/shared/_errors.html.erb
<%= provide(:errors_messages) do  %>

	<% if object_error.errors.full_messages then %>	
		<div class="message-main-container">
			<div class="message-container">
				<ul class="list-errors">						
					<% object_error.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>		
				</ul>
			</div>
		</div>
	<% end %>

<% end %>

app/views/shared/_errors_category.html.erb
<%= provide(:errors_messages) do  %>

	<% if object_error then %>	
		<div class="message-main-container">
			<div class="message-container">
				<ul class="list-errors">						
					<% object_error.each do |msg| %>
						<li><%= msg %></li>
					<% end %>		
				</ul>
			</div>
		</div>
	<% end %>

<% end %>

app/views/shared/_footer.html.erb
<article class="footer-container-main">
    <section class="sectin-1">

        <div class="footer-header">
            <span>О проекте</span>
        </div>
        <div class="footer-text">
            <p>
            Данный сайт является учебным проектом, посвящённым учету личных финансов. Цель проекта — показать основы организации личного бюджета и принципы управления денежными средствами.
            </p>
            <br>
            <p>
            Сайт не предназначен для оказания коммерческих услуг или продажи продуктов. Вся представленная информация носит исключительно ознакомительный характер и предназначена исключительно для образовательных целей.
            </p>
            <br>            
            <p>
            Спасибо за интерес к проекту! Любые замечания и пожелания можно отправлять на почту lichnye_finansy@internet.ru.                
            </p>
        </div>

    </section>

    <section class="sectin-2">

        <div class="footer-header">
            <span>Ссылки</span>
        </div>

        <div class="footer-container-links">
            <div class="footer-text">
                <ul class="footer-list-links">
                    <li><%= link_to('Главная', root_path, class: 'footer-link') %></li>
                    <li><%= link_to('О проекте', '/about', class: 'footer-link') %></li>
                    <li><%= link_to('Вход в аккаунт', new_session_path, class: 'footer-link') %></li>
                    <li><%= link_to('Регистрация', new_user_path, class: 'footer-link') %></li>                    
                </ul>
            </div>

        <% if user_signed_in?%>
            
            <div class="footer-text">
                <ul class="footer-list-links">
                    <li><%= link_to('Новый учет', new_accounting_object_path, class: 'footer-link') %></li>
                    <li><%= link_to('Ваши объекты учета', accounting_object_index_path, class: 'footer-link') %></li>
                    <li><%= link_to('Информация', user_path('user'), class: 'footer-link') %></li>
                </ul>
            </div>

        <% end %>
            
        </div>

    </section>

    <section class="sectin-3">

        <div class="footer-header">
            <span>Контакты</span>
        </div>
        <div class="footer-text">
            <div class="footer-contacts">
                <span>Mail</span>
                <span>lichnye_finansy@internet.ru</span>
            </div>

            <div class="footer-contacts">
                <span>Github</span>
                <span>
                <%= link_to('https://github.com/RikersMax', 
                'https://github.com/RikersMax', 
                target: '_blank', 
                rel: 'noopener noreferrer') 
                %> 
                </span>
            </div>            
        </div>

    </section>    
</article> 

app/views/shared/_message.html.erb
<div class="message-main-container-flash">
	<div class="message-container-flash">
		<p><%= flash[:message] %></p>	
	</div>
</div>

app/views/shared/_navbar.html.erb
<article class="nav-bar-header-contaier-main">
	<nav class="nav-bar-container">
		<div class="guest-contianer-logo">
			<a href="/" class="guest-contianer-logo" style="text-decoration: none; color: #000; padding-top: 0.25em;">
				<%= image_tag("logo.png", class: 'navbar-logo') %>
			</a>
		</div>

		<ul class="nav-bar-list-links">

			<% if user_signed_in?%>
				<li><%= link_to('Новый учет', new_accounting_object_path, class: 'nav-bar-link') %></li>
				<li><%= link_to('Ваши объекты учета', accounting_object_index_path, class: 'nav-bar-link') %></li>				
			<% end %>
				
			<li><%= link_to('О проекте', '/about', class: 'nav-bar-link') %></li>

		</ul>

		<%= render(partial: 'shared/dropdown_menu') %>

	</nav>
</article>