config/routes.rb
Rails.application.routes.draw do
 
  root('guests#index')
  get('/about', to: 'guests#about')

  resources(:users, only: %i[index new show edit create update])
  resources(:accounting_object, except: %i[create])
  resources(:categories, except: %i[new show])
  resources(:operations, except: %i[show])

  resource(:session, only: %i[new create destroy])
  #resource(:password_reset, only: %i[new create edit update])

  post('accounting_object_psot', to: 'accounting_object#create', as: 'accounting_object_post')

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :accounting_object
  has_one :operation, dependent: :destroy

  validates(:color_category, format: {with: /\A#[0-9A-Fa-f]{3,6};\z/, message: "неверный формат цвета"})
  validates(:name_category, {presence: true, length: {minimum: 2, maximum: 64}})
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

    @acc_object_encript = params[:accounting_object_id]
    
    acc_object_decript = Base64.decode64(@acc_object_encript)    

    user = User.find_by(remember_token_digest: session[:user_id])
    @acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, @acc_object) #проверка

    @form_category = Category.new
    @form_category.accounting_object = @acc_object

    @pagy, @category_list = pagy(Category.where(accounting_object_id: @acc_object.id), limit: 8)
  end

  def create

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object_decript = Base64.decode64(params[:category][:accounting_object_id])    
    @acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, @acc_object)

    @form_category = Category.new(name_category: params[:category][:name_category], 
      accounting_object_id: @acc_object.id,
      color_category: params[:category][:color_category])

    if @form_category.save then
      flash[:message] = 'category created'
      redirect_to(categories_path(accounting_object_id: params[:category][:accounting_object_id]))
    else
      category_name_placeholder = @form_category.name_category
      category_errors = @form_category.errors.full_messages
      redirect_to(categories_path(
        accounting_object_id: params[:category][:accounting_object_id], 
        category_errors: category_errors,
        category_name_placeholder: category_name_placeholder
        ))
    end    
   
  end

  def edit
 
    @acc_object_encript = params[:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)    

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, acc_object) #проверка

    category_id_decript = Base64.decode64(params[:id])
    @category = Category.find(category_id_decript)
    
  end

  def update
    category_update = Category.find(params[:id])

    user = User.find_by(remember_token_digest: session[:user_id])
    acc_object_decript = Base64.decode64(params[:category][:accounting_object_id])    
    @acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, @acc_object)

    attributes_update = {name_category: params[:category][:name_category], 
      accounting_object_id: @acc_object.id,
      color_category: params[:category][:color_category]
    }

    if category_update.update(attributes_update) then
      flash[:message] = 'category update'
      redirect_to(categories_path(accounting_object_id: params[:category][:accounting_object_id]))
    else
      @acc_object_encript = params[:category][:accounting_object_id]
      @category = category_update
      
      render(:edit)
    end
       
  end

  def destroy
    category_delete = Category.find(params[:id])

    user = User.find_by(remember_token_digest: session[:user_id])
    @acc_object_decript = Base64.decode64(params[:accounting_object_id])    
    @acc_object = AccountingObject.find(@acc_object_decript)

    check_user_request(user, @acc_object)

    if category_delete.delete then
      flash[:message] = 'category delete'
      redirect_to(categories_path(accounting_object_id: params[:accounting_object_id]))
    else
      @acc_object_encript = params[:accounting_object_id]
      @category = category_update
      flash[:message] = '2 error form categories#create'
      render(:edit)
    end
    
  end


  private

  def check_user_request(user, acc_object)
    if acc_object.user == user then
      return
    else
      flash[:message] = '1 error from categories#check user'
      redirect_to(root_path)
    end
  end
end

app/views/categories/_form.html.erb
<% if category_model.persisted? then%>

	<% render('shared/errors', object_error: category_model )%>

<% else %>

	<% render('shared/errors_category', object_error:  params[:category_errors] ) %>

<% end %>

<div class="user-setting-header size-xl">
	<span><%= category_model.persisted? ? t('btn.upd_category') : t('btn.add_category') %></span>
</div>

<%= form_with(model: category_model, method: method_action, data: { turbo: false }) do |f| %>

	<div class="show-categories-date-fields ">								
		<%= f.label(:name_category, t('form.name_category'))  %>
		<%= f.text_field(:name_category, 
			placeholder: 'Категория', 
			value: (category_model.persisted? ? category_model.name_category : params[:category_name_placeholder]), 
			required: true
		) %>
	</div>

	<div hidden>
		<%= f.hidden_field(:accounting_object_id, value: @acc_object_encript)  %>
	</div>						

	<div class="colors-palette-container">

		<div style="text-align: center;">
			<span>Выбор цвета</span>
		</div>
		
		<div class="form-radio-btn-container">

			<div class="form-radio-btn-category">
				<input id="radio-category-color-1" type="radio" name="category[color_category]" value="#93DAFB;" checked>
				<label for="radio-category-color-1" id="radio-category-color-1-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-2" type="radio" name="category[color_category]" value="#ffb3b3;">
				<label for="radio-category-color-2" id="radio-category-color-2-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-3" type="radio" name="category[color_category]" value="#dd99ff;">
				<label for="radio-category-color-3" id="radio-category-color-3-label" ></label>
			</div>
	    </div>

	    <div class="form-radio-btn-container">
			<div class="form-radio-btn-category">
				<input id="radio-category-color-4" type="radio" name="category[color_category]" value="#ffccff;">
				<label for="radio-category-color-4" id="radio-category-color-4-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-5" type="radio" name="category[color_category]" value="#b3ffff;">
				<label for="radio-category-color-5" id="radio-category-color-5-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-6" type="radio" name="category[color_category]" value="#99ff99;">
				<label for="radio-category-color-6" id="radio-category-color-6-label" ></label>
			</div>
		</div>

		<div class="form-radio-btn-container">
			<div class="form-radio-btn-category">
				<input id="radio-category-color-7" type="radio" name="category[color_category]" value="#ffaa80;">
				<label for="radio-category-color-7" id="radio-category-color-7-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-8" type="radio" name="category[color_category]" value="#80ffcc;">
				<label for="radio-category-color-8" id="radio-category-color-8-label" ></label>
			</div>

			<div class="form-radio-btn-category">
				<input id="radio-category-color-9" type="radio" name="category[color_category]" value="#000000;">
				<label for="radio-category-color-9" id="radio-category-color-9-label" ></label>
			</div>
		</div>

	</div>


	<div style="text-align: center;">
		<%= f.submit(category_model.persisted? ? t('btn.update') : t('btn.create'), class: 'btn-date-show size-xl')  %>
	</div>

<% end %>

app/views/categories/_show_table.html.erb
<div id="container-table-categories">
	<table class="accounting-category-table">
		<thead>
			<tr>
				<th><%= t('table.number') %></th>
				<th><%= t('table.category') %></th>
				<th><%= t('table.color') %></th>
				<th><%= t('table.edit') %></th>
				<th><%= t('table.delte') %></th>
			</tr>
		</thead>
		<tbody>
			<% category_list.each_with_index do |category, i|  %>
			<tr>
				<td><%= i + 1 %></td>
				<td><%= category.name_category %></td>
				<td class="color_category"><div style="background-color: <%=category.color_category  %>;"></div></td>
				<td><%= link_to(t('btn.edit'), edit_category_path(id: Base64.encode64(category.id.to_s), accounting_object_id: @acc_object_encript)) %></td>
				<td><%= button_to(t('btn.delete'), category, 
				{method: :delete,
				class: 'btn-delete-category',				 
				params: {accounting_object_id: @acc_object_encript}								
				}
				) %></td>
			</tr>	
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="5"><%== pagy_nav(@pagy) %></td>
			</tr>
		</tfoot>			
	</table>
</div>

<script>

// Добавляем слушатель события загрузки документа
document.addEventListener('DOMContentLoaded', function() {
  // Получаем все формы с классом button_to
  var forms = document.querySelectorAll('form.button_to');

  // Проходим по каждой форме
  forms.forEach(function(form) {
    // Добавляем обработчик события submit
    form.addEventListener('submit', function(event) {
      // Прекращаем стандартную отправку формы
      event.preventDefault();

      // Показываем окно подтверждения
      if (confirm('Вы уверены что хотите удалить категорию?')) {
        // Отправляем форму вручную, если подтверждено
        this.submit();
      }
    });
  });
});

</script>

app/views/categories/edit.html.erb
<article class="content-container-main-center">
	<section class="content-section">
		<div class="show-container-category-edit">					
			<div class="show-container-category-section-edit">
				<%= render(partial: 'form', locals: {category_model: @category, method_action: 'PATCH' })  %>
			</div>
		</div>
	</section>
</article>		

app/views/categories/index.html.erb
<article class="content-container-main-center">
	<div>
	</div>
	<section class="content-section">
		<div>
			<%= link_to('Назад', accounting_object_path(Base64.encode64(@acc_object.id.to_s)), class: 'btn-category-back-acc')  %>
		</div>
		<div class="show-main-container-accounting">
			<div class="category-header-container">
				<span class="category-header-name"><%= @acc_object.name_object %></span>
				<div>
					<span class="show-category-type-object-<%= @acc_object.type_object_id%>">
						<%= t("acc_boject.#{@acc_object.type_object.name_type}") %>
					</span>
				</div>
			</div>

			<div class="show-container-accounting">					
				<div class="show-container-category-section-left">
					<%= render(partial: 'form', locals: {category_model: @form_category, method_action: 'POST'})  %>
				</div>

				<div class="show-container-category-section-reight">
					<%= render(partial: 'show_table', locals: {category_list: @category_list})  %>
				</div>
			</div>
		</div>
	</section>
</article>	