config/routes.rb
Rails.application.routes.draw do
 
  root('guests#index')
  get('/about', to: 'guests#about')

  resources(:users, only: %i[index new show edit create update])
  resources(:accounting_object, except: %i[create])
  resources(:categories, except: %i[new show])
  resources(:operations, except: %i[show])

  resource(:session, only: %i[new create destroy])
  #resource(:password_reset, only: %i[new create edit update])

  post('accounting_object_psot', to: 'accounting_object#create', as: 'accounting_object_post')

end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :accounting_object
  belongs_to :category

  validates(:accounting_object_id, presence: true)
  validates(:category_id, presence: true)
  validates(:amount_of_money, numericality: { greater_than_or_equal_to: 0 }, allow_nil: false)
  #validates(:data_stamp, {date_time: true})
  validates(:description, length: { maximum: 1000 }, allow_blank: true)

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

  before_action(:require_authentication)

  def index
  end

  def new
    @acc_object_encript = params[:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)
    categories_all = Category.where(accounting_object_id: acc_object_decript)
    @select_categories = categories_all.inject([]) {|arr, item| arr.push([item.name_category, item.id])}

    @operation = Operation.new

  end

  def show
  end

  def create

    user = User.find_by(remember_token_digest: session[:user_id])

    @acc_object_encript = params[:operation][:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)
    acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, acc_object)

    operation_params = {}
    operation_params[:accounting_object_id] = acc_object_decript
    operation_params[:amount_of_money] = params[:operation][:amount_of_money]
    operation_params[:category_id] = params[:operation][:category_id]
    operation_params[:data_stamp] = params[:operation][:data_stamp]
    operation_params[:description] = params[:operation][:description]

    @operation = Operation.new(operation_params)

    #render(plain: operation)

    if @operation.save then
      flash[:message] = 'operation create'      
      redirect_to(accounting_object_path(id: @acc_object_encript))
    else
      categories_all = Category.where(accounting_object_id: acc_object_decript)
      @select_categories = categories_all.inject([]) {|arr, item| arr.push([item.name_category, item.id])}
      #flash[:message] = @operation.errors.full_messages
      render(:new)
    end
   
  end

  def edit   
    user = User.find_by(remember_token_digest: session[:user_id])

    @acc_object_encript = params[:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)
    acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, acc_object)

    categories_all = Category.where(accounting_object_id: acc_object_decript)
    @select_categories = categories_all.inject([]) {|arr, item| arr.push([item.name_category, item.id])}

    @operation = Operation.find(Base64.decode64(params[:id]))
    @operation_encod = params[:id]

  end

  def update


    user = User.find_by(remember_token_digest: session[:user_id])
    @acc_object_encript = params[:operation][:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)
    acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, acc_object)

    attributes_update = {amount_of_money: params[:operation][:amount_of_money], 
      accounting_object_id: acc_object_decript,
      category_id: params[:operation][:category_id],
      data_stamp: params[:operation][:data_stamp],
      description: params[:operation][:description]
    }

    @operation = Operation.find(Base64.decode64(params[:operation][:id_encod_operation]))

    if @operation.update(attributes_update) then
      flash[:message] = 'operation update'      
      redirect_to(accounting_object_path(id: @acc_object_encript))
    else
      categories_all = Category.where(accounting_object_id: acc_object_decript)
      @select_categories = categories_all.inject([]) {|arr, item| arr.push([item.name_category, item.id])}
      flash[:message] = 'error operation#update'
      render(:new)
    end
  end

  def destroy
    user = User.find_by(remember_token_digest: session[:user_id])
    @acc_object_encript = params[:accounting_object_id]
    acc_object_decript = Base64.decode64(@acc_object_encript)
    acc_object = AccountingObject.find(acc_object_decript)

    check_user_request(user, acc_object)

    operation_encod = params[:id]
    operation = Operation.find(Base64.decode64(params[:id]))


    if operation.destroy then
      flash[:message] = 'operation delete'
      redirect_to(accounting_object_path(@acc_object_encript))
    else
      flash[:message] = '2 error from operation#delete'
      render(:new)
    end
  end

  private

  def check_user_request(user, acc_object)
    if acc_object.user == user then
      return
    else
      flash[:message] = '1 error from categories#check user'
      redirect_to(root_path)
    end
  end
end

app/views/operations/_form.html.erb
<% render('shared/errors', object_error: operation )%>

<div class="content-form-container-operation">

	<%= form_with(model: operation, data: { turbo: false }) do |f| %>
		
		<%= f.hidden_field(:accounting_object_id, value: @acc_object_encript)  %>
				
		<%= f.hidden_field(:id_encod_operation, value: id_encod_operation) if id_encod_operation.present? %>			
		
	
		<div class="text-bottom-create-object size-xxl">
			<span><%= operation.persisted? ? t('btn.edit') : t('btn.create') %>	запись</span>	
		</div>

		<div class="form-container-field-object">
			<%= f.label(:amount_of_money, 'Сумма', class: 'm-top-m size-xl')  %>
			<%= f.number_field(:amount_of_money, 
			in: (0.00..999_999_999.99),
			step: (0.01),
			class: 'form-input-create-object size-xl m-top-s',
			placeholder: '00.0') %>
		</div>


		<div class="form-select-container-object m-bot-xl">
	    	<div style="display: grid; place-items: center;">
	    		<span class="size-xl">Категория: </span>
	    	</div>

	    	<div>
	    		<%if  @select_categories.empty? then  %>
	    			<%= link_to(t('btn.add_category'), 
	    			categories_path(accounting_object_id: @acc_object_encript), 
	    			class: 'btn-user-action')  %>
	    		<% else %>
	    			<%= f.select('category_id', @select_categories)  %>
	    		<% end %>
	    	</div>
	    </div>

	    <div class="form-select-container-object m-top-xl">
	    	<div style="display: grid; place-items: center;">
				<%= f.label(:data_stamp,  t('form.date_stamp') + ':', class: 'm-top-m size-xl')  %>
	    	</div>
	    	<div>
				<%= f.date_field(:data_stamp, value: Time.now, class: 'form-input-create-object size-xl m-top-s') %>
	    	</div>
		</div>

		<div class="form-container-field-object m-top-xl">
			<%= f.label(:description, t('form.description'), class: 'm-top-m size-xl')  %>
			<%= f.text_area(:description, class: 'form-input-text-area m-top-s', size: "20x5") %>
		</div>
		
		<div class="form-container-field-object m-bot-l m-top-l">			
			<%= f.submit(operation.persisted? ? t('btn.update') : t('btn.create'), class: 'btn-create-object m-top-l')  %>
		</div>
		
	<% end %>

	<% if operation.persisted? then %>

		<div>
    	<hr class="drop-line-form">
    </div>
	
		<div class="form-container-field-object m-bot-l m-top-m">
			<%= button_to(t('btn.delete'), operation_path(operation_encod), method: :delete, 
				class: 'btn-delete-object', 
				id: 'delete-button',
				params:{accounting_object_id: @acc_object_encript}
				)  %>
		</div>
	<% end %>
	
</div>


<script>
    document.getElementById("delete-button").addEventListener("click", function(event){
      event.preventDefault(); // Предотвращаем стандартное поведение отправки формы
      
      if(confirm("Вы действительно хотите удалить эту запись?")) {
        this.form.submit(); // Отправляем форму, если пользователь подтвердил удаление
      }
    });
</script>

app/views/operations/edit.html.erb
<article class="content-container-main-center">
	<section class="content-section-operation">
		<%= render(partial: 'form', 
		locals: {operation: @operation, 
			operation_encod: @operation_encod, 
			id_encod_operation: @operation_encod}
		)  %>
	</section>
</article>		

app/views/operations/index.html.erb
<article class="content-container-main-center">
	<section class="content-section-operation">
		<div style="margin-top: 3em;">
			<%= link_to('Ваши список объектов', accounting_object_index_path, class: 'btn-user-action') %>
		</div>
	</section>
</article>		

app/views/operations/new.html.erb
<article class="content-container-main-center">
	<section class="content-section-operation">
		<%# link_to('Назад', accounting_object_path(@acc_object_encript), class: 'btn-operation-back-acc')  %>
	
		<%= render(partial: 'form', 
		locals: {operation: @operation,
			id_encod_operation: false}
		)  %>
	</section>
</article>		